# Generated by Django 2.2.1 on 2019-06-25 07:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='todo.Tag'),
            preserve_default=False,
        ),
    ]
